In [1]:
import pandas as pd
from tqdm import tqdm
import codecs
import sys
import os

In [86]:
hasocdf = pd.read_csv('data/hasoc19_hindi_dataset/hasoc2019_hi_test_gold_2919.tsv', sep='\t', header=0)

In [87]:
hasocdf

,text_id,text,task_1,task_2,task_3
0,hasoc_hi_5061,"वक्त, इन्सान और इंग्लैंड का मौसम आपको कभी भी ध...",NOT,NONE,NONE
1,hasoc_hi_2090,#कांग्रेस के इस #कमीने की #करतूत को देखिए देश ...,HOF,OFFN,TIN
2,hasoc_hi_2960,पाकिस्तान को फेकना था फेका गया। जो हार कर भी द...,HOF,OFFN,TIN
3,hasoc_hi_864,जो शब्द तूम आज किसी और औरत के लिए यूज कर रहे व...,NOT,NONE,NONE
4,hasoc_hi_54,नेता जी हम समाजवादी सिपाही हमेशा आपके साथ है आ...,NOT,NONE,NONE
...,...,...,...,...,...
1313,hasoc_hi_2773,यह काला सूअर भी तो 10 जनपद का टॉयलेट साफ करने ...,HOF,PRFN,UNT
1314,hasoc_hi_7231,बेटा यह सवाल अपनी अम्मी से पूछना जवाब में असल...,HOF,OFFN,TIN
1315,hasoc_hi_769,आप को तो पाकिस्तान मे होना चाहिए वहा जो यादव क...,HOF,PRFN,TIN
1316,hasoc_hi_5725,विजयमालिया ललितमोदी नीरवमोदी आसारामबापू बाबारा...,HOF,HATE,UNT
1317,hasoc_hi_2519,"अप्रतिम ,अद्वत ,असाधारण पराक्रम से भारत को गौर...",NOT,NONE,NONE

In [7]:
hdf2 = pd.read_csv('data/hasoc19_hindi_dataset/hindi_dataset.tsv', sep='\t', header=0)

In [13]:
cosaidf = pd.read_excel('data/constraintai_hindi_dataset/constraint_Hindi_Train.xlsx', header=0)

In [15]:
cosaidf2 = pd.read_excel('data/constraintai_hindi_dataset/Test Set Complete.xlsx', header=0)

In [16]:
cosaidf3 =pd.read_excel('data/constraintai_hindi_dataset/Constraint_Hindi_Valid.xlsx', header=0)

In [155]:
cosaidf

,Unique ID,Post,Labels Set
0,1,मेरे देश के हिन्दु बहुत निराले है। कुछ तो पक्क...,"hate,offensive"
1,2,सरकार हमेशा से किसानों की कमाई को बढ़ाने के लि...,non-hostile
2,3,"सुशांत ने जो बिजनेस डील 9 जून को की थी, वो डील...",non-hostile
3,4,@prabhav218 साले जेएनयू छाप कमिने लोग हिन्दुओं...,"defamation,offensive"
4,5,#unlock4guidelines - अनलॉक-4 के लिए गाइडलाइन्स...,non-hostile
...,...,...,...
5723,5724,उदितराज जी हिम्मत जुटा कर उस नेता के लिए कुछ ...,hate
5724,5725,उप्र: पीएम रिपोर्ट में खुलासा: हार्टअटैक से हु...,non-hostile
5725,5726,नौकरी गंवा चुके दोस्त की मदद: नगद के बजाए गिफ्...,non-hostile
5726,5727,बंगाल में हिन्दू मरे हैं इसलिए मुझे कोई फर्क न...,fake
5727,5728,रक्षा मंत्री @rajnathsingh ने पूर्व राष्ट्रपति...,non-hostile

In [60]:
hcheckdf = pd.read_csv('data/HateCheckHIn/monolingual_functionalities.csv', header=0)

In [61]:
hcheckdf

,test_case,label,target,functionality
0,मुझे हिन्दुओं से नफरत है.,hateful,Hindu,1
1,मुझे मुसलमानों से नफरत है.,hateful,Muslim,1
2,मुझे बांग्लादेशियों से नफरत है.,hateful,Bangladeshi,1
3,मुझे पाकिस्तानियों से नफरत है.,hateful,Pakistani,1
4,मुझे हिजड़ों से नफरत है.,hateful,Eunuch,1
...,...,...,...,...
4749,क्या आपको एहसास नहीं है कि दलितों को रेंडी कह ...,nonhateful,Dalit,21
4750,क्या आपको एहसास नहीं है कि महिलाओं को रेंडी कह...,nonhateful,Woman,21
4751,क्या आपको एहसास नहीं है कि निचली जात के लोगों ...,nonhateful,Lower Caste,21
4752,क्या आपको एहसास नहीं है कि अंग्रेज़ों को रेंडी ...,nonhateful,British,21
4753,क्या आपको एहसास नहीं है कि समलैंगिक लोगो को रे...,nonhateful,Homosexual,21

In [62]:
hcheckdf['text'] = hcheckdf.test_case
hcheckdf['label_yn'] = hcheckdf.label.apply(lambda x: 1 if x == 'hateful' else 0)

In [63]:
hcheckdf

,test_case,label,target,functionality,text,label_yn
0,मुझे हिन्दुओं से नफरत है.,hateful,Hindu,1,मुझे हिन्दुओं से नफरत है.,1
1,मुझे मुसलमानों से नफरत है.,hateful,Muslim,1,मुझे मुसलमानों से नफरत है.,1
2,मुझे बांग्लादेशियों से नफरत है.,hateful,Bangladeshi,1,मुझे बांग्लादेशियों से नफरत है.,1
3,मुझे पाकिस्तानियों से नफरत है.,hateful,Pakistani,1,मुझे पाकिस्तानियों से नफरत है.,1
4,मुझे हिजड़ों से नफरत है.,hateful,Eunuch,1,मुझे हिजड़ों से नफरत है.,1
...,...,...,...,...,...,...
4749,क्या आपको एहसास नहीं है कि दलितों को रेंडी कह ...,nonhateful,Dalit,21,क्या आपको एहसास नहीं है कि दलितों को रेंडी कह ...,0
4750,क्या आपको एहसास नहीं है कि महिलाओं को रेंडी कह...,nonhateful,Woman,21,क्या आपको एहसास नहीं है कि महिलाओं को रेंडी कह...,0
4751,क्या आपको एहसास नहीं है कि निचली जात के लोगों ...,nonhateful,Lower Caste,21,क्या आपको एहसास नहीं है कि निचली जात के लोगों ...,0
4752,क्या आपको एहसास नहीं है कि अंग्रेज़ों को रेंडी ...,nonhateful,British,21,क्या आपको एहसास नहीं है कि अंग्रेज़ों को रेंडी ...,0
4753,क्या आपको एहसास नहीं है कि समलैंगिक लोगो को रे...,nonhateful,Homosexual,21,क्या आपको एहसास नहीं है कि समलैंगिक लोगो को रे...,0

In [64]:
hcheckdf[['text', 'label_yn']]

                                                   text  label_yn
0                             मुझे हिन्दुओं से नफरत है.         1
1                            मुझे मुसलमानों से नफरत है.         1
2                       मुझे बांग्लादेशियों से नफरत है.         1
3                        मुझे पाकिस्तानियों से नफरत है.         1
4                               मुझे हिजड़ों से नफरत है.         1
...                                                 ...       ...
4749  क्या आपको एहसास नहीं है कि दलितों को रेंडी कह ...         0
4750  क्या आपको एहसास नहीं है कि महिलाओं को रेंडी कह...         0
4751  क्या आपको एहसास नहीं है कि निचली जात के लोगों ...         0
4752  क्या आपको एहसास नहीं है कि अंग्रेज़ों को रेंडी ...         0
4753  क्या आपको एहसास नहीं है कि समलैंगिक लोगो को रे...         0

[4754 rows x 2 columns]

In [65]:
def generate_unique_id(prefix, counter):
    return f'{prefix}_{counter}'

In [66]:
hcheckdf['uid'] = hcheckdf.index.map(lambda x: generate_unique_id('hcheck_hi_train', x))

In [67]:
hcheckdf.index = hcheckdf.uid

In [68]:
hcheckdf[['text', 'label_yn']].to_csv('data/aggregated/hindi/hcheck.csv')

In [44]:
macddf_train = pd.read_csv('data/MACD/dataset/hindi_train.csv', header=0)

In [45]:
macddf_train

       label                                               text
0          0                      भीड़ में  बहुत  हब्सी मिलेंगे
1          0          साले बेवकूफ अपनी मां मक्खियां  तो हटा दें
2          0                   बुर देदो तो मुह में लंड ले लो तो
3          0               कुत्ता वहा है चिल्ला तू क्यों रहा है
4          1          चाय नहीं पीता हूं मैं इसी को छोड़ दिया ok
...      ...                                                ...
20178      0             और छोटे भी क्यु पहनते हो, कहा जरूरत है
20179      1             कैसी हो सोना क्या आप हमसे दोस्ती करोगी
20180      1          इस से ये पता चलता है अब चुनाव आ रहा है🙄🙄🙄
20181      1                    खेत जोते हुए किसान भैंस के साथो
20182      0  काश आगर यह इतना दिमाग पढाई में लगायें तो शायद ...

[20183 rows x 2 columns]

In [74]:
macddf_val

,label,text,uid,label_yn
uid,,,,
macd_hi_val_0,0,Comment box चालू कर झवाडे,macd_hi_val_0,1
macd_hi_val_1,0,"आपके पास पुख्ता सबूत है, क्या या फिर कुछ भी। उ...",macd_hi_val_1,1
macd_hi_val_2,1,👬दोस्ती होती है – One Time 🙃 हम निभाते है – So...,macd_hi_val_2,0
macd_hi_val_3,1,चाय लवर डाॅ. को छोड़ देगे or mo. कोई छोड़ नहीं...,macd_hi_val_3,0
macd_hi_val_4,1,जो अनपढ़ लोग दिन-रात हिंदू मुस्लिम करते रहते ह...,macd_hi_val_4,0
...,...,...,...,...
macd_hi_val_6723,1,माय लवर बोलो तो,macd_hi_val_6723,0
macd_hi_val_6724,1,वेरी गुड नाईस वीडियो आपने बनाई है आप पुराने सो...,macd_hi_val_6724,0
macd_hi_val_6725,1,हाय सेक्सी लग रही हो,macd_hi_val_6725,0
macd_hi_val_6726,1,बढ़ा चोखा है ❤❤,macd_hi_val_6726,0
macd_hi_val_6727,0,माधर्चोद तुम लोग शेरनी शेरनी नहीं गीदड़ पाल के...,macd_hi_val_6727,1

In [47]:
macddf_test = pd.read_csv('data/MACD/dataset/hindi_test.csv', header=0)
macddf_val = pd.read_csv('data/MACD/dataset/hindi_val.csv', header=0)

In [54]:
macddf_train['uid'] = macddf_train.index.map(lambda x: generate_unique_id('macd_hi_train', x))
macddf_test['uid'] = macddf_test.index.map(lambda x: generate_unique_id('macd_hi_test', x))
macddf_val['uid'] = macddf_val.index.map(lambda x: generate_unique_id('macd_hi_val', x))

In [70]:
macddf_train['label_yn'] = macddf_train.label.apply(lambda x: 1 if x == 0 else 0)
macddf_test['label_yn'] = macddf_test.label.apply(lambda x: 1 if x == 0 else 0)
macddf_val['label_yn'] = macddf_val.label.apply(lambda x: 1 if x == 0 else 0)

In [73]:
macddf_train.index = macddf_train.uid
macddf_test.index = macddf_test.uid
macddf_val.index = macddf_val.uid

In [81]:
macddf_test[['text', 'label_yn']].to_csv('data/aggregated/hindi/macd_hi_test.csv')
macddf_train[['text', 'label_yn']].to_csv('data/aggregated/hindi/macd_hi_train.csv')
macddf_val[['text', 'label_yn']].to_csv('data/aggregated/hindi/macd_hi_val.csv')

In [79]:
macddf = pd.concat([macddf_train, macddf_test, macddf_val], axis=0)

In [82]:
macddf[['text', 'label_yn']].to_csv('data/aggregated/hindi/macd_hi.csv')

In [88]:
hasocdf

,text_id,text,task_1,task_2,task_3
0,hasoc_hi_5061,"वक्त, इन्सान और इंग्लैंड का मौसम आपको कभी भी ध...",NOT,NONE,NONE
1,hasoc_hi_2090,#कांग्रेस के इस #कमीने की #करतूत को देखिए देश ...,HOF,OFFN,TIN
2,hasoc_hi_2960,पाकिस्तान को फेकना था फेका गया। जो हार कर भी द...,HOF,OFFN,TIN
3,hasoc_hi_864,जो शब्द तूम आज किसी और औरत के लिए यूज कर रहे व...,NOT,NONE,NONE
4,hasoc_hi_54,नेता जी हम समाजवादी सिपाही हमेशा आपके साथ है आ...,NOT,NONE,NONE
...,...,...,...,...,...
1313,hasoc_hi_2773,यह काला सूअर भी तो 10 जनपद का टॉयलेट साफ करने ...,HOF,PRFN,UNT
1314,hasoc_hi_7231,बेटा यह सवाल अपनी अम्मी से पूछना जवाब में असल...,HOF,OFFN,TIN
1315,hasoc_hi_769,आप को तो पाकिस्तान मे होना चाहिए वहा जो यादव क...,HOF,PRFN,TIN
1316,hasoc_hi_5725,विजयमालिया ललितमोदी नीरवमोदी आसारामबापू बाबारा...,HOF,HATE,UNT
1317,hasoc_hi_2519,"अप्रतिम ,अद्वत ,असाधारण पराक्रम से भारत को गौर...",NOT,NONE,NONE

In [89]:
hdf2

,text_id,text,task_1,task_2,task_3
0,hasoc_hi_5556,"बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...",NOT,NONE,NONE
1,hasoc_hi_5648,सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...,HOF,PRFN,UNT
2,hasoc_hi_164,तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...,HOF,PRFN,TIN
3,hasoc_hi_3530,"बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...",NOT,NONE,NONE
4,hasoc_hi_5206,चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...,NOT,NONE,NONE
...,...,...,...,...,...
4660,hasoc_hi_6606,पाकिस्तान ने हिंदुओं के ख़िलाफ़ बोलने वाले को ...,NOT,NONE,NONE
4661,hasoc_hi_4931,कोहली है #नेहरू नहीं जो अंग्रेजों के तलवे चाटन...,HOF,PRFN,TIN
4662,hasoc_hi_1059,परशुराम? वही जिसने अपनी मां की हत्या की थीं?,NOT,NONE,NONE
4663,hasoc_hi_5429,जिस देश में #कन्हैया_कुमार जैसा पढ़ा लिखा युवा...,HOF,HATE,TIN
4664,hasoc_hi_1656,इनके बापों मैं भी दम नहीं जो भारत को इस्लामिक ...,HOF,HATE,TIN

In [92]:
hdf = pd.concat([hasocdf, hdf2], axis=0, ignore_index=True)
hdf

,text_id,text,task_1,task_2,task_3
0,hasoc_hi_5061,"वक्त, इन्सान और इंग्लैंड का मौसम आपको कभी भी ध...",NOT,NONE,NONE
1,hasoc_hi_2090,#कांग्रेस के इस #कमीने की #करतूत को देखिए देश ...,HOF,OFFN,TIN
2,hasoc_hi_2960,पाकिस्तान को फेकना था फेका गया। जो हार कर भी द...,HOF,OFFN,TIN
3,hasoc_hi_864,जो शब्द तूम आज किसी और औरत के लिए यूज कर रहे व...,NOT,NONE,NONE
4,hasoc_hi_54,नेता जी हम समाजवादी सिपाही हमेशा आपके साथ है आ...,NOT,NONE,NONE
...,...,...,...,...,...
5978,hasoc_hi_6606,पाकिस्तान ने हिंदुओं के ख़िलाफ़ बोलने वाले को ...,NOT,NONE,NONE
5979,hasoc_hi_4931,कोहली है #नेहरू नहीं जो अंग्रेजों के तलवे चाटन...,HOF,PRFN,TIN
5980,hasoc_hi_1059,परशुराम? वही जिसने अपनी मां की हत्या की थीं?,NOT,NONE,NONE
5981,hasoc_hi_5429,जिस देश में #कन्हैया_कुमार जैसा पढ़ा लिखा युवा...,HOF,HATE,TIN
5982,hasoc_hi_1656,इनके बापों मैं भी दम नहीं जो भारत को इस्लामिक ...,HOF,HATE,TIN

In [95]:
hdf.rename(columns={"text_id": "uid"}, inplace=True)
hdf

,uid,text,task_1,task_2,task_3
0,hasoc_hi_5061,"वक्त, इन्सान और इंग्लैंड का मौसम आपको कभी भी ध...",NOT,NONE,NONE
1,hasoc_hi_2090,#कांग्रेस के इस #कमीने की #करतूत को देखिए देश ...,HOF,OFFN,TIN
2,hasoc_hi_2960,पाकिस्तान को फेकना था फेका गया। जो हार कर भी द...,HOF,OFFN,TIN
3,hasoc_hi_864,जो शब्द तूम आज किसी और औरत के लिए यूज कर रहे व...,NOT,NONE,NONE
4,hasoc_hi_54,नेता जी हम समाजवादी सिपाही हमेशा आपके साथ है आ...,NOT,NONE,NONE
...,...,...,...,...,...
5978,hasoc_hi_6606,पाकिस्तान ने हिंदुओं के ख़िलाफ़ बोलने वाले को ...,NOT,NONE,NONE
5979,hasoc_hi_4931,कोहली है #नेहरू नहीं जो अंग्रेजों के तलवे चाटन...,HOF,PRFN,TIN
5980,hasoc_hi_1059,परशुराम? वही जिसने अपनी मां की हत्या की थीं?,NOT,NONE,NONE
5981,hasoc_hi_5429,जिस देश में #कन्हैया_कुमार जैसा पढ़ा लिखा युवा...,HOF,HATE,TIN
5982,hasoc_hi_1656,इनके बापों मैं भी दम नहीं जो भारत को इस्लामिक ...,HOF,HATE,TIN

In [123]:
hdf['label_yn'] = hdf.task_1.apply(lambda x: 1 if x == 'HOF' else 0)

In [98]:
hdf.index = hdf.uid

In [124]:
hdf[['text', 'label_yn']].loc[hasocdf.index].to_csv('data/aggregated/hasoc_hi_t1_test.csv')
hdf[['text', 'label_yn']].loc[hdf2.index].to_csv('data/aggregated/hasoc_hi_t1_train.csv')

In [100]:
hdf[['text', 'label_yn']].to_csv('data/aggregated/hasoc_hi_t1.csv')

In [120]:
hdf.label_yn = hdf.task_2.apply(lambda x: 1 if x == 'HATE' else 0)

In [102]:
hdf

,uid,text,task_1,task_2,task_3,label_yn
uid,,,,,,
hasoc_hi_5061,hasoc_hi_5061,"वक्त, इन्सान और इंग्लैंड का मौसम आपको कभी भी ध...",NOT,NONE,NONE,0
hasoc_hi_2090,hasoc_hi_2090,#कांग्रेस के इस #कमीने की #करतूत को देखिए देश ...,HOF,OFFN,TIN,0
hasoc_hi_2960,hasoc_hi_2960,पाकिस्तान को फेकना था फेका गया। जो हार कर भी द...,HOF,OFFN,TIN,0
hasoc_hi_864,hasoc_hi_864,जो शब्द तूम आज किसी और औरत के लिए यूज कर रहे व...,NOT,NONE,NONE,0
hasoc_hi_54,hasoc_hi_54,नेता जी हम समाजवादी सिपाही हमेशा आपके साथ है आ...,NOT,NONE,NONE,0
...,...,...,...,...,...,...
hasoc_hi_6606,hasoc_hi_6606,पाकिस्तान ने हिंदुओं के ख़िलाफ़ बोलने वाले को ...,NOT,NONE,NONE,0
hasoc_hi_4931,hasoc_hi_4931,कोहली है #नेहरू नहीं जो अंग्रेजों के तलवे चाटन...,HOF,PRFN,TIN,0
hasoc_hi_1059,hasoc_hi_1059,परशुराम? वही जिसने अपनी मां की हत्या की थीं?,NOT,NONE,NONE,0
hasoc_hi_5429,hasoc_hi_5429,जिस देश में #कन्हैया_कुमार जैसा पढ़ा लिखा युवा...,HOF,HATE,TIN,1
hasoc_hi_1656,hasoc_hi_1656,इनके बापों मैं भी दम नहीं जो भारत को इस्लामिक ...,HOF,HATE,TIN,1

In [103]:
hdf[['text', 'label_yn']].to_csv('data/aggregated/hasoc_hi_t2.csv')

In [109]:
hdf.loc[hasocdf.index]

,uid,text,task_1,task_2,task_3,label_yn
text_id,,,,,,
hasoc_hi_5061,hasoc_hi_5061,"वक्त, इन्सान और इंग्लैंड का मौसम आपको कभी भी ध...",NOT,NONE,NONE,0
hasoc_hi_2090,hasoc_hi_2090,#कांग्रेस के इस #कमीने की #करतूत को देखिए देश ...,HOF,OFFN,TIN,0
hasoc_hi_2960,hasoc_hi_2960,पाकिस्तान को फेकना था फेका गया। जो हार कर भी द...,HOF,OFFN,TIN,0
hasoc_hi_864,hasoc_hi_864,जो शब्द तूम आज किसी और औरत के लिए यूज कर रहे व...,NOT,NONE,NONE,0
hasoc_hi_54,hasoc_hi_54,नेता जी हम समाजवादी सिपाही हमेशा आपके साथ है आ...,NOT,NONE,NONE,0
...,...,...,...,...,...,...
hasoc_hi_2773,hasoc_hi_2773,यह काला सूअर भी तो 10 जनपद का टॉयलेट साफ करने ...,HOF,PRFN,UNT,0
hasoc_hi_7231,hasoc_hi_7231,बेटा यह सवाल अपनी अम्मी से पूछना जवाब में असल...,HOF,OFFN,TIN,0
hasoc_hi_769,hasoc_hi_769,आप को तो पाकिस्तान मे होना चाहिए वहा जो यादव क...,HOF,PRFN,TIN,0
hasoc_hi_5725,hasoc_hi_5725,विजयमालिया ललितमोदी नीरवमोदी आसारामबापू बाबारा...,HOF,HATE,UNT,1
hasoc_hi_2519,hasoc_hi_2519,"अप्रतिम ,अद्वत ,असाधारण पराक्रम से भारत को गौर...",NOT,NONE,NONE,0

In [107]:
hasocdf.index = hasocdf.text_id

In [118]:
hdf2.index = hdf2.text_id

In [137]:
cosaidf3[cosaidf3['Labels Set'].apply(lambda x: 'hate' in x or 'offensive' in x)]

,Unique ID,Post,Labels Set
12,13,भाई जाके हिन्दू भाइयों की मदद कर जिनकी नौकरी च...,offensive
15,16,रेट फिक्स है\n\nकृप्या मोल भाव न करें।\n\n #शा...,"hate,offensive"
21,22,नागरिकता संशोधन विधेयक के विरोध में जिन पार्टि...,hate
31,32,ये कमीना बातें बड़ी बड़ी करता है मगर हरकत सड़क...,"hate,offensive"
35,36,बॉलीवुड में हो सकता है अनुराग जैसे और भी गंदे ...,"hate,offensive"
...,...,...,...
780,781,अभी शाम को मुझे एक कांग्रेसी चमचा मिला और बोला...,hate
796,797,RT @ReshmaHindusta1: जो उखाड़ना था वो तो उखाड़...,offensive
797,798,"कंगना तू बिमार हें, तुझे इलाज की जरूरत हें.",offensive
799,800,रेट फिक्स\nशाहीन बाग__ 500 रुपये\n72हुरो के पा...,offensive
806,807,@ThePushpendra_ चंद फेंके हुए टुकड़ों के लिए ह...,hate

In [146]:
def get_labelled_dataset(train, test, val):
    train_h = train[train['Labels Set'].apply(lambda x: 'hate' in x or 'offensive' in x)]
    test_h = test[test['Labels Set'].apply(lambda x: 'hate' in x or 'offensive' in x)]
    val_h = val[val['Labels Set'].apply(lambda x: 'hate' in x or 'offensive' in x)]

    train_nh = train[train['Labels Set'].apply(lambda x: 'non-hostile' in x)]
    test_nh = test[test['Labels Set'].apply(lambda x: 'non-hostile' in x)]
    val_nh = val[val['Labels Set'].apply(lambda x: 'non-hostile' in x)]

    train_h['label_yn'] = 1
    train_nh['label_yn'] = 0
    test_h['label_yn'] = 1
    test_nh['label_yn'] = 0
    val_h['label_yn'] = 1
    val_nh['label_yn'] = 0

    train_h['uid'] = train_h['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_train', x))
    test_h['uid'] = test_h['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_test', x))
    val_h['uid'] = val_h['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_val', x))
    train_nh['uid'] = train_nh['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_train', x))
    test_nh['uid'] = test_nh['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_test', x))
    val_nh['uid'] = val_nh['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_val', x))

    train_h.index = train_h.uid
    test_h.index = test_h.uid
    val_h.index = val_h.uid
    train_nh.index = train_nh.uid
    test_nh.index = test_nh.uid
    val_nh.index = val_nh.uid

    train_df = pd.concat([train_h, train_nh], axis=0)
    test_df = pd.concat([test_h, test_nh], axis=0)
    val_df = pd.concat([val_h, val_nh], axis=0)

    train_df['text'] = train_df.Post
    test_df['text'] = test_df.Post
    val_df['text'] = val_df.Post

    return train_df[['text', 'label_yn']], test_df[['text', 'label_yn']], val_df[['text', 'label_yn']]

In [147]:
cds = get_labelled_dataset(cosaidf, cosaidf2, cosaidf3)

/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_h['label_yn'] = 1
/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_nh['label_yn'] = 0
/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_h['label_yn'] = 1
/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_nh['label_yn'] = 0
/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_h['label_yn'] = 1
/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_nh['label_yn'] = 0
/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_h['uid'] = train_h['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_train', x))
/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_h['uid'] = test_h['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_test', x))
/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_h['uid'] = val_h['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_val', x))
/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_nh['uid'] = train_nh['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_train', x))
/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_nh['uid'] = test_nh['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_test', x))
/var/folders/5p/f3v16qj1041_w6pr1yxsdp_w0000gn/T/ipykernel_46499/237533967.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_nh['uid'] = val_nh['Unique ID'].apply(lambda x: generate_unique_id('constai_hi_val', x))

In [150]:
cds[0]

,text,label_yn
uid,,
constai_hi_train_1,मेरे देश के हिन्दु बहुत निराले है। कुछ तो पक्क...,1
constai_hi_train_4,@prabhav218 साले जेएनयू छाप कमिने लोग हिन्दुओं...,1
constai_hi_train_11,RT @_Pb_swain_: मोदीजी और जब सारा देश सेना के ...,1
constai_hi_train_12,RT @ShilpiSinghINC: 48000 घरों को तोड़ने का आद...,1
constai_hi_train_15,आजम खान की बेटी पर ससूर ने किया रेप।\nअब quata...,1
...,...,...
constai_hi_train_5721,#RheaChakraborty के फोन से जो व्हाट्सएप चैट के...,0
constai_hi_train_5722,मध्यप्रदेश में 50 हजार से भी ज्यादा कोरोना केस...,0
constai_hi_train_5725,उप्र: पीएम रिपोर्ट में खुलासा: हार्टअटैक से हु...,0
constai_hi_train_5726,नौकरी गंवा चुके दोस्त की मदद: नगद के बजाए गिफ्...,0
constai_hi_train_5728,रक्षा मंत्री @rajnathsingh ने पूर्व राष्ट्रपति...,0

In [152]:
cds[0].to_csv('data/aggregated/hindi/cosaaai_hi_train.csv')
cds[1].to_csv('data/aggregated/hindi/cosaaai_hi_test.csv')
cds[2].to_csv('data/aggregated/hindi/cosaaai_hi_val.csv')

In [153]:
cds_df = pd.concat(cds, axis=0)

In [156]:
cds_df.to_csv('data/aggregated/hindi/cosaaai_hi.csv')

In [157]:
cds_df

,text,label_yn
uid,,
constai_hi_train_1,मेरे देश के हिन्दु बहुत निराले है। कुछ तो पक्क...,1
constai_hi_train_4,@prabhav218 साले जेएनयू छाप कमिने लोग हिन्दुओं...,1
constai_hi_train_11,RT @_Pb_swain_: मोदीजी और जब सारा देश सेना के ...,1
constai_hi_train_12,RT @ShilpiSinghINC: 48000 घरों को तोड़ने का आद...,1
constai_hi_train_15,आजम खान की बेटी पर ससूर ने किया रेप।\nअब quata...,1
...,...,...
constai_hi_val_804,ऐसा है पूर्व राष्ट्रपति प्रणब मुखर्जी का परिवा...,0
constai_hi_val_805,UP BEd Entrance Exam Result: यूपी बीएड प्रवेश ...,0
constai_hi_val_806,अनलॉक 4 में किस तरह की सावधानी बरतनी है ?\n\n#...,0
constai_hi_val_809,औरंगाबाद में फिर धीरे-धीरे पांव पसार रहा कोरोन...,0
constai_hi_val_810,"बाइस्कोप: कादर के संवादों का कमाल, डिंपल की कल...",0

#### Data Aggregation

In [158]:
files = [
    'data/aggregated/hindi/hcheck.csv',
    'data/aggregated/hindi/cosaaai_hi.csv',
    'data/aggregated/hindi/hasoc_hi_t1.csv',
    'data/aggregated/hindi/hasoc_hi_t2.csv',
    'data/aggregated/hindi/macd_hi.csv'
]

In [165]:
df1 = pd.read_csv(files[0], index_col='uid')
df2 = pd.read_csv(files[1], index_col='uid')
df3 = pd.read_csv(files[2], index_col='uid')
df4 = pd.read_csv(files[3], index_col='uid')
df5 = pd.read_csv(files[4], index_col='uid')

In [172]:
df = pd.concat([df1,df2,df3,df4,df5], axis=0)

In [173]:
df.to_csv('data/aggregated/hindi/hate-classifier-hindi.csv')